### ISSUE TITLE
Data provider: what database to store data

### ISSUE THREAD

**Issue by nicola** [densekernel/3001#5]
I suppose MongoDB we can just throw stuff into and not care much about the structure of data.
This would simplify #4 since there are existing rest library, discuss

**Comment by SnubbleJr** [comment]
I Think a simple SQLite would work, I can design the structure if you want.

**Comment by nicola** [comment]
Thing is that there is no reason to be bound to the data scheme especially if we want to move fast. Whoever is taking this, will possibly be in the data provider team, so it's good you all agree on this

**Comment by himerzi** [comment]
I'd suggest using a hosted solution. Particularly because later on this will have to integrate with the work the visualisation team is doing - and you guys don't want to be re-inventing the wheel when it comes to exposing your SQLite DB to the front end.

What about using something like [Firebase](https://www.firebase.com/), Parse, or [MongoLab](https://mongolab.com/) (this is probably the most "powerful" solution out of the three). Or indeed a hosted SQLite provider. All of these have Javascript SDK's that we could easily integrate with on the Vis team.

**Comment by xalodni** [comment]
<a href = "http://rethinkdb.com/">Rethinkdb</a> can do joins unlike Mongodb.

**Comment by nicola** [comment]
Getting experimental here @xalodni. I agree with @himerzi, the least we can do on this, the more we can focus on the core product.

**Comment by nicola** [comment]
Ok, @navidhg chosed MySQL
